#!/usr/bin/env python3
"""从消费者导出的事件 CSV 生成滚动微观结构特征。

该脚本只用于离线探索和训练集原型，输入按 symbol 独立排序并计算，避免不同合约
在换月或多标的回放时相互污染特征窗口。
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="CSV generated by kafka_consumer.py")
    parser.add_argument("output", type=Path, help="Destination feature CSV")
    parser.add_argument("--window", type=int, default=50, help="滚动观察窗口大小，至少为 5")
    return parser.parse_args()


def extract_features(frame: pd.DataFrame, window: int) -> pd.DataFrame:
    """返回保留原始列并附加收益、波动率、订单流和简易信号的 DataFrame。

订单流以 BUY 为正、SELL 为负；未知方向为零。``realized_vol`` 和 z-score 在
窗口样本不足时为缺失值，最终 ``signal`` 将其填为零，避免训练数据出现无穷值。
"""
    frame = frame.copy()
    frame["event_time"] = pd.to_datetime(frame["event_time"], utc=True)
    frame["price"] = pd.to_numeric(frame["price"], errors="coerce")
    frame["quantity"] = pd.to_numeric(frame["quantity"], errors="coerce").fillna(0.0)
    frame = frame.sort_values(["symbol", "event_time"])

    # 所有滚动窗口都必须限制在同一具体 symbol 内，不能穿透合约边界。
    grouped = frame.groupby("symbol", group_keys=False)
    frame["return_1"] = grouped["price"].pct_change()
    frame["realized_vol"] = grouped["return_1"].transform(
        lambda values: values.rolling(window, min_periods=max(5, window // 5)).std()
    )
    side_sign = frame["side"].map({"BUY": 1.0, "SELL": -1.0}).fillna(0.0)
    frame["signed_quantity"] = frame["quantity"] * side_sign
    frame["order_flow"] = frame.groupby("symbol")["signed_quantity"].transform(
        lambda values: values.rolling(window, min_periods=1).sum()
    )
    flow_mean = frame.groupby("symbol")["order_flow"].transform(
        lambda values: values.rolling(window, min_periods=5).mean()
    )
    flow_std = frame.groupby("symbol")["order_flow"].transform(
        lambda values: values.rolling(window, min_periods=5).std()
    )
    frame["order_flow_zscore"] = (frame["order_flow"] - flow_mean) / flow_std.replace(0, pd.NA)
    frame["momentum"] = grouped["price"].pct_change(window)
    frame["signal"] = (frame["order_flow_zscore"].clip(-3, 3) / 3).fillna(0.0)
    return frame


def main() -> None:
    args = parse_args()
    if args.window < 5:
        raise SystemExit("--window must be at least 5")
    source = pd.read_csv(args.input)
    features = extract_features(source, args.window)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    features.to_csv(args.output, index=False)
    print(f"rows={len(features)} output={args.output}")


if __name__ == "__main__":
    main()
